import { createClient, type SupabaseClient, type User } from "npm:@supabase/supabase-js@2";
export const corsHeaders={"access-control-allow-origin":Deno.env.get("ALLOWED_ORIGIN")||"https://iederees-create.github.io","access-control-allow-headers":"authorization, apikey, content-type","access-control-allow-methods":"POST, OPTIONS","content-type":"application/json"};
export class HttpError extends Error{constructor(public status:number,public code:string,message:string){super(message)}}
export function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:corsHeaders})}
export async function authenticate(req:Request){const token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"");if(!token)throw new HttpError(401,"unauthorized","A bearer token is required.");const client=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:`Bearer ${token}`}}});const {data,error}=await client.auth.getUser(token);if(error||!data.user)throw new HttpError(401,"unauthorized","The session is invalid or expired.");return {user:data.user,client}}
export function adminClient(){return createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!)}
export async function requireRole(db:SupabaseClient,user:User,roles:string[]){const {data}=await db.from("user_roles").select("role").eq("user_id",user.id).in("role",roles);if(!data?.length)throw new HttpError(403,"forbidden","This role cannot perform the action.")}
export async function parseObject(req:Request,required:string[]){let body:unknown;try{body=await req.json()}catch{throw new HttpError(400,"invalid_json","Request body must be JSON.")}if(!body||typeof body!=="object"||Array.isArray(body))throw new HttpError(422,"invalid_body","Request body must be an object.");for(const key of required)if(!(key in body))throw new HttpError(422,"missing_field",`Missing required field: ${key}`);return body as Record<string,unknown>}
export async function rateLimit(...args:[SupabaseClient,string,number]){void args;/* Hook: replace with atomic RPC or gateway-backed limiter before production. */}
export async function audit(db:SupabaseClient,user:User,action:string,targetId?:string,detail:Record<string,unknown>={}){const {error}=await db.from("audit_logs").insert({actor_id:user.id,action,target_table:"edge_function",target_id:targetId||null,detail});if(error)throw new HttpError(500,"audit_failed","The operation was not completed because its audit record failed.")}
export type FunctionConfig={name:string;roles:string[];required:string[];rateLimit:number;action:string};
export function serve(config:FunctionConfig,operation:(ctx:{body:Record<string,unknown>;user:User;admin:SupabaseClient})=>Promise<unknown>){Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:corsHeaders});if(req.method!=="POST")return json({error:{code:"method_not_allowed",message:"Use POST."}},405);try{const {user}=await authenticate(req);const admin=adminClient();await requireRole(admin,user,config.roles);await rateLimit(admin,`${config.name}:${user.id}`,config.rateLimit);const body=await parseObject(req,config.required);const data=await operation({body,user,admin});await audit(admin,user,config.action,typeof body.id==="string"?body.id:undefined,{function:config.name});return json({data})}catch(error){const e=error instanceof HttpError?error:new HttpError(500,"internal_error","The request could not be completed.");return json({error:{code:e.code,message:e.message}},e.status)}})}
